
<style type="text/css">table.tableizer-table {
	border: 1px solid #CCC;
	font-family: Arial, Helvetica, sans-serif;
	border-collapse: collapse;
}

.tableizer-table td {
	padding: 4px;
	margin: 3px;
	border: 1px solid #CCC;
}

.tableizer-table th {
	background-color: #104E8B;
	color: #FFF;
	font-weight: bold;
}
table tr td:first-child {
	width: 1rem;
}
table tr td[colspan]:first-child {
	width: 100%;
}
</style>
<table class="tableizer-table" >
	<thead>
		<tr class="tableizer-firstrow">
			<th colspan="5" style="text-align: center;height: 1.5rem;">推 荐 书 单--家长书单</th>
		</tr>
	</thead>
	<tbody>
			<tr>
			<td>序号</td><td>书名</td><td>作者</td><td>出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">育儿主题1</td>
		</tr>
		<tr>
			<td>1</td><td>《好妈妈胜过好老师》文字版</td><td>尹建莉</td><td>作家出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>2</td><td>《好妈妈胜过好老师》图文版</td><td>尹建莉</td><td>浙江文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>3</td><td>《最美的教育最简单》</td><td>尹建莉</td><td>作家出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>4</td><td>《自由的孩子最自觉》</td><td>尹建莉</td><td>百花洲文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>5</td><td>《好孩子：三分天注定，七分靠教育》</td><td>洪兰著/尹建莉主编</td><td>长江文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>6</td><td>《爱弥儿》</td><td>卢梭著/李平沤 译</td><td>上海人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>7</td><td>《夏山学校》</td><td>A.S.尼尔著/王克难 译</td><td>新星出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>8</td><td>《夏山学校的百年故事》</td><td>（英）沃恩</td><td>教育科学出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>9</td><td>《夏山学校毕业生》</td><td>侯赛因·卢卡斯 著</td><td>华东师范大学出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>10</td><td>《第56号教室的奇迹》</td><td>（美）雷夫艾斯奎斯　著</td><td>光明日报出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">育儿主题2：</td>
		</tr>
		<tr>
			<td>1</td><td>《小王子》</td><td>尹建莉译</td><td>新蕾出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>2</td><td>《顺应心理，孩子更合作》</td><td>维尼</td><td>青岛出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>3</td><td>《敢让孩子做自己》</td><td>少年商学院 编才</td><td>湖北教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>4</td><td>《父母是孩子最好的音乐老师》</td><td>郑又慧</td><td>作家出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>5</td><td>《发现孩子》</td><td>(意)玛丽亚·蒙台梭利</td><td>中国妇女出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>6</td><td>《蒙台梭利的早期教育法》</td><td>&nbsp;</td><td>中国妇女出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>7</td><td>《蒙台梭利儿童教育手册》</td><td>&nbsp;</td><td>中国青少年出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>8</td><td>《家庭中的儿童》</td><td>&nbsp;</td><td>中国发展出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>9</td><td>《有吸收力的心灵》</td><td>&nbsp;</td><td>中国妇女出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>10</td><td>《儿童的自发成长》</td><td>&nbsp;</td><td>天津社会科学院出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>11</td><td>《陪孩子走过小学六年》</td><td>刘称莲</td><td>北京联合出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>12</td><td>《遇见孩子遇见更好的自己》</td><td>（美）高夫/托马斯/切瓦特桑著</td><td>新世界出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>13</td><td>《无条件养育》</td><td>（美）科恩　著</td><td>天津教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>14</td><td>《孩子把你的手给我》</td><td>（美）吉诺特 著</td><td>京化出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>15</td><td>《接纳孩子》</td><td>小巫 </td><td>广西科学技术出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>16</td><td>《早教的秘密》</td><td>李子勋</td><td>中信出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>17</td><td>《童年的秘密》</td><td>玛利亚蒙台梭利</td><td>天津社会科学院出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>18</td><td>《朗读手册》</td><td>吉姆·崔利斯 著</td><td>南海出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">育儿主题3：</td>
		</tr>
		<tr>
			<td>1</td><td>《再忙也要做个好爸爸》</td><td>迈克尔·史密斯</td><td>江苏文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>2</td><td>《和你一起，我不怕老去》</td><td>刘继荣</td><td>北京日报出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>3</td><td>《坐在路边鼓掌的人》</td><td>刘继荣</td><td>中信出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>4</td><td>《培养孩子从画画开始》</td><td>（日）鸟居昭美</td><td>漓江出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>5</td><td>《不能错过的英语启蒙》</td><td>安妮鲜花　著</td><td>外语教学与研究出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>6</td><td>《当我遇见一个人》</td><td>李雪</td><td>北京联合出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>7</td><td>《给孩子的10个最伟大礼物》</td><td>（美）范诺伊　著</td><td>京华出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>8</td><td>《外公家书》</td><td>陈德勤、陈允斌</td><td>北京联合出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>9</td><td>《孩子生病怎么办？》</td><td>那唐元</td><td>知识出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">心理疗愈&哲学主题</td>
		</tr>
		<tr>
			<td>1</td><td>《烦恼都是自找的》</td><td>学诚法师</td><td>中国友谊出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>2</td><td>《快乐就这么简单》</td><td>&nbsp;</td><td>华文出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>3</td><td>《放下是舍更是得》</td><td>&nbsp;</td><td>华文出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>4</td><td>《半路出家》</td><td>刘书宏（贤书法师）</td><td>长江文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>5</td><td>《不完美，才美》</td><td>海蓝博士</td><td>北京联合出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>6</td><td>《不完美，才美》2</td><td>海蓝博士</td><td>广东人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>7</td><td>《好好说话》</td><td>学诚法师</td><td>广东人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>8</td><td>《一切都是最好的安排》</td><td>加措仁波切</td><td>中国友谊出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>9</td><td>《一切都是最好的安排》2</td><td>加措仁波切</td><td>国际文化出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>10</td><td>《人生随时可以重来》</td><td>摩西奶奶著</td><td>北京日报出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>11</td><td>《遇见未知的自己》</td><td>张德芬</td><td>湖南文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>12</td><td>《人生不较劲》</td><td>周国平</td><td>广西师范大学出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>13</td><td>《经历过，才懂得》</td><td>吴淡如</td><td>北京联合出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>14</td><td>《与神对话》</td><td>尼尔唐纳德沃尔什 著</td><td>江西人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>15</td><td>《生命沉思录》</td><td>曲黎敏</td><td>长江文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>16</td><td>《恰到好处的幸福》</td><td>毕淑敏</td><td>湖南文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>17</td><td>《为何家会伤人》</td><td>武志红</td><td>北京联合出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>18</td><td>《身体知道答案》</td><td>武志红</td><td>鹭江出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>19</td><td>《感谢自己的不完美》</td><td>武志红</td><td>中国华侨出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">其他/生活类：</td>
		</tr>
		<tr>
			<td>1</td><td>《愿你被这世界温柔相待》</td><td>叶萱 </td><td>百花洲文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>2</td><td>《一个人的朝圣》</td><td>【英】蕾秋·乔伊斯 著</td><td>北京联合出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>3</td><td>《三毛典藏全集》</td><td>三毛　著</td><td>北京十月文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>4</td><td>《逝者如渡渡》</td><td>申赋渔</td><td>湖南人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>5</td><td>《乖，摸摸头》</td><td>大冰</td><td>湖南文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>7</td><td>《断舍离》</td><td>[日]山下英子 著</td><td>广西科学技术出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>8</td><td>《女心理师》</td><td>毕淑敏　 </td><td>重庆出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>9</td><td>《追风筝的人》</td><td>［美］卡勒德·胡赛尼 </td><td>上海人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>10</td><td>《秘密》</td><td>（澳）拜恩</td><td>湖南文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>11</td><td>《斯通纳》</td><td>[美]约翰·威廉斯 著</td><td>上海人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>12</td><td>《老子》</td><td>汤漳平，王朝华 译注</td><td>中华书局</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>13</td><td>《诗经》</td><td>王秀梅　译注</td><td>中华书局</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>14</td><td>《明朝那些事儿》</td><td>当年明月</td><td>北京联合出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td colspan="5" style="background-color: #104E8B;color: #FFF;font-weight: bold;height: 1.5rem;">推 荐 书 单--孩子书单</td>
		</tr>
		<tr>
			<td>序号</td><td>书名</td><td>作者</td><td>出版社</td><td>年龄段</td>
		</tr>
		<tr>
			<td  colspan="5" style="color: red;height:1.5rem">绘本——分类主题：</td>
		</tr>
		<tr>
			<td>1</td><td>《大卫不可以》</td><td>〔美〕大卫·香农</td><td>北京联合出版公司</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>2</td><td>《大卫上学去》</td><td>〔美〕大卫·香农</td><td>北京联合出版公司</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>3</td><td>《大卫惹麻烦》</td><td>〔美〕大卫·香农</td><td>北京联合出版公司</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>4</td><td>《大卫，圣诞节到啦》</td><td>〔美〕大卫·香农</td><td>北京联合出版公司</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>5</td><td>《我不知道我是谁》</td><td>乔恩·布莱克</td><td>新星出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>6</td><td>《我也可以飞》</td><td>让罗姆·瑞利亚</td><td>湖北美术出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>7</td><td>《阿立会穿裤子了》</td><td>神泽利子</td><td>明天出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>8</td><td>《我爱幼儿园》</td><td>赛尔日·布洛克</td><td>北京科学技术出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>9</td><td>《不学写字有坏处》</td><td>方素珍</td><td>电子工业出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>10</td><td>《毛头小鹰》</td><td>罗勃卡鲁斯</td><td>明天出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>11</td><td>《你很特别》</td><td>陆可铎</td><td>中央广播电视大学出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>12</td><td>《花婆婆》</td><td>〔美〕芭芭拉库尼</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>13</td><td>《小小聪明豆绘本》系列</td><td>阿克塞尔·舍夫勒等</td><td>外语教学与研究出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>14</td><td>《斯凯瑞金色童书》系列</td><td>（美）斯凯瑞</td><td>贵州人民出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>15</td><td>《小鸡鸡的故事》</td><td>山本直英</td><td>连环画出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>16</td><td>《小威向前冲》</td><td>(英)艾伦 著；李小强 译</td><td>贵州人民出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>17</td><td>《呀，屁股》</td><td>[丹麦]迈普里斯·安徒生</td><td>希望出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>18</td><td>《乳房的故事》</td><td>（日）土屋麻由美　 </td><td>连环画出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>19</td><td>《你感觉怎么样？》</td><td>安东尼·布朗</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>20</td><td>《走开，绿色大怪物》</td><td>安德华·恩贝尔利</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>21</td><td>《小猫头鹰》</td><td>马丁·韦尔德</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>22</td><td>《吃掉黑暗的怪兽》</td><td>乔伊斯·邓巴</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>23</td><td>《安的种子》</td><td>王早早</td><td>海燕出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>24</td><td>《苏和的白马》</td><td>(日)大塚勇三</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>25</td><td>《好消息！坏消息！》</td><td>杰夫·麦克</td><td>江苏文艺出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>26</td><td>《生气汤》</td><td>贝西·艾芙瑞</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>27</td><td>《啊哈！》</td><td>杰夫·麦克</td><td>江苏文艺出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>28</td><td>《蚕豆大哥的快乐一天》</td><td>中屋美和</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>29</td><td>《弗洛拉和火烈鸟》</td><td>莫莉艾德尔绘</td><td>长江少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>30</td><td>《菲菲生气了》</td><td>〔美〕莫莉·卞　著</td><td>河北教育出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>31</td><td>《克里克塔》</td><td> 汤米·温格尔 </td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>32</td><td>《乌云之上有晴空》</td><td>（美）罗伯特·恩莱特</td><td>化学工业出版社</td><td>6-12岁</td>
		</tr>
		<tr>
			<td>33</td><td>《我不是完美小孩》</td><td>几米　著</td><td>海豚出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>34</td><td>《小兔汤姆》系列</td><td>[法]玛丽—阿利娜·巴文</td><td>海燕出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>35</td><td>《和朋友们一起想办法》系列</td><td>[英]加比·戈尔德萨克</td><td>湖北美术出版社</td><td>4-7岁</td>
		</tr>
		<tr>
			<td>36</td><td>《儿童情绪管理与性格培养绘本》系列</td><td>[美]贝丝·安德鲁斯</td><td>化学工业出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>37</td><td>《幸福的小土豆》系列</td><td> 甘特·塞杰斯</td><td>海豚出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>38</td><td>《聪明豆绘本》系列</td><td>（英）莎伦·瑞特　等著</td><td>外语教学与研究出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>39</td><td>《暖暖心绘本》系列</td><td>（伊朗）米拦弗特毕</td><td>湖南少儿出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>40</td><td>《小兔汤姆成长的烦恼图画书》</td><td>（法）玛莉-阿丽娜·巴文 </td><td>海燕出版社</td><td>3岁+</td>
		</tr>
		<tr>
			<td>41</td><td>《海豚绘本花园》系列</td><td>&nbsp;</td><td>湖北美术出版社</td><td>3岁+</td>
		</tr>
		<tr>
			<td>42</td><td>《小猪小象》系列</td><td>莫·威廉斯　文/图</td><td>国际文化出版公司</td><td>3岁+</td>
		</tr>
		<tr>
			<td>43</td><td>《我的日记系列》</td><td>高洪波 等</td><td>中国少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>44</td><td>《暖房子经典绘本》系列</td><td>共八辑</td><td>云南出版集团公司 晨光出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>45</td><td>《大象小不点》系列</td><td>(奥)莫泽尔　著</td><td>南海出版公司</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>46</td><td>《爸爸，你爱我吗》</td><td>芭芭拉·M·宙斯</td><td>长江少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>47</td><td>《抱抱》</td><td>杰兹·阿波罗</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>48</td><td>《我长大以后》</td><td>余治莹</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>49</td><td>《隧道》</td><td>安东尼·布朗</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>50</td><td>《你最喜欢谁》</td><td>内田麟太郞</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>51</td><td>《妈妈心妈妈树》</td><td>方素珍</td><td>浙江少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>52</td><td>《爷爷的幸福口令》</td><td>西本鸡介</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>53</td><td>《逃家小兔》</td><td>玛格丽特·怀兹·布朗</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>54</td><td>《猜猜我有多爱你》</td><td>山姆·麦克布·雷尼</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>55</td><td>《团圆》</td><td>余丽琼</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>56</td><td>《我和老爸》</td><td>莉兹·克里莫</td><td>长江少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>57</td><td>《我爸爸》</td><td>安东尼·布朗</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>58</td><td>《我妈妈》</td><td>安东尼·布朗</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>59</td><td>《爷爷一定有办法》</td><td>菲比·吉尔曼　 </td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>60</td><td>《嗨，我喜欢你》</td><td>戴文婷</td><td>北京联合出版公司</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>61</td><td>《小熊和最好的爸爸》</td><td>（荷）丹姆 著</td><td>贵州人民出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>62</td><td>《父与子》全集</td><td>埃·奥 卜劳恩</td><td>辽海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>63</td><td>《大噪门妈妈》</td><td>[德]尤塔·保尔 </td><td>新蕾出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>64</td><td>《快乐爸爸》</td><td>[德]菲利普·韦希特尔</td><td>新蕾出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>65</td><td>《驴小弟变石头》</td><td>[美]威廉·史塔克　 </td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>66</td><td>《爱心伴我长大》</td><td>[比]让娜·德蒂斯</td><td>湖北少儿出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>67</td><td>《最温暖的爱》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>68</td><td>《小动物大智慧》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>69</td><td>《一起去冒险》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>70</td><td>《小黑鱼》</td><td>李欧·李奥尼</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>71</td><td>《石头汤》</td><td>琼·穆特</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>72</td><td>《好朋友》</td><td>赫姆·海恩</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>73</td><td>《凯琪的包裹》</td><td>坎达丝·弗莱明</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>74</td><td>《园丁》</td><td>萨拉·斯图尔特</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>75</td><td>《我有友情要出租》</td><td>方素珍</td><td>新疆青少年出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>76</td><td>《狼婆婆》</td><td>杨志成</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>77</td><td>《做个爱书人》</td><td>芭芭拉·伯特纳</td><td>青岛出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>78</td><td>《换妈妈》</td><td>白冰　著，江显英　绘</td><td>中国少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>79</td><td>《妈妈发火了》</td><td>（韩）崔琡僖　编</td><td>天津人民美术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>80</td><td>《奶奶的红披风》</td><td>[美]萝伦卡斯提罗　著</td><td>中信出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>81</td><td>《让路给小鸭子》</td><td>（美）麦克洛斯基　编绘</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>82</td><td>《鸭子骑车记》</td><td>大卫·夏农</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>83</td><td>《手不是用来打人的》系列</td><td>"（美）玛丁妮阿加西博士；</td>
		</tr>
		<tr>
			<td>伊丽莎白弗迪克　著"</td><td>新世界出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>84</td><td>《不一样的卡梅拉》系列</td><td>法）克利斯提昂 约里波瓦著</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>85</td><td>《和朋友们一起想办法》系列</td><td>（英）戈尔德萨克　编</td><td>湖北美术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>86</td><td>《一园青菜成了精》</td><td>北方童谣</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>87</td><td>《小蓝和小黄》</td><td>李欧·李奥尼</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>88</td><td>《不可思议的旅程》</td><td>艾伦贝克尔</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>89</td><td>《天天星期三》</td><td>方素珍</td><td>浙江少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>90</td><td>《田鼠阿佛》</td><td>李欧·李奥尼</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>91</td><td>《红气球》</td><td>埃拉·马俐</td><td>连环画出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>92</td><td>《雪人》</td><td>雷蒙·布力格</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>93</td><td>《野兽国》</td><td>莫里斯·桑达克</td><td>贵州人民出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>94</td><td>《点点点》</td><td>埃尔维·杜莱</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>95</td><td>《想要不一样》</td><td>童嘉</td><td>贵州人民出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>96</td><td>《小仙女艾丽斯》</td><td>大卫·香农</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>97</td><td>《100层的房子》</td><td>（日）岩井俊雄</td><td>北京科学技术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>98</td><td>《神奇糖果店》</td><td>宫西达也</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>99</td><td>《晴天有时下猪》系列</td><td>矢玉四郎</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>100</td><td>《威利的画》</td><td>安东尼·布朗</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>101</td><td>《跟着线走》</td><td>朗菲斯特</td><td>新世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>102</td><td>《彩虹色的花》</td><td>细野绫子</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>103</td><td>《好饿的毛毛虫》</td><td>艾瑞·卡尔</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>104</td><td>《点》</td><td>彼得·雷诺兹</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>105</td><td>《艾玛画画》</td><td>凯·塞尔曼</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>106</td><td>《阿罗有枝彩色笔》</td><td>约翰逊</td><td>接力出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>107</td><td>《我的连衣裙》</td><td>西卷茅子</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>108</td><td>《棕色的熊、棕色的熊，你在看什么》</td><td>艾瑞·卡尔</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>109</td><td>《美术馆奇遇》</td><td>玛戈达莱娜·格毫·于连</td><td>连环画出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>110</td><td>《小猫玫瑰》</td><td>皮欧特·魏尔康</td><td>少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>111</td><td>《天空在脚下》</td><td>埃米莉·阿诺德·麦卡力</td><td>河北教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>112</td><td>《灰王子》</td><td>芭贝·柯尔</td><td>北京联合出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>113</td><td>《爱花的牛》</td><td>曼罗·里夫</td><td>21世纪出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>114</td><td>《朱家故事》</td><td>安东尼·布朗</td><td>河北教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>115</td><td>《最完美的王子》</td><td>保罗·哈里森</td><td>浙江少年儿童出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>116</td><td>《纸袋公主》</td><td>罗伯特·廖斯克</td><td>河北教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>117</td><td>《穿毛衣的小镇》</td><td>麦克·巴内特</td><td>接力出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>118</td><td>《勇敢的艾琳》</td><td>威廉·史塔克</td><td>21世纪出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>119</td><td>《顽皮公主不出嫁》</td><td>芭贝·柯尔</td><td>南海出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>120</td><td>《乖乖小恶魔》</td><td>希亚文·奥拉姆</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>121</td><td>《先左脚，再右脚》</td><td>汤姆·狄波拉</td><td>河北教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>122</td><td>《祝你生日快乐》</td><td>方素珍</td><td>浙江少年儿童出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>123</td><td>《第一次上街买东西》</td><td>简井赖子</td><td>新星出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>124</td><td>《没关系没关系》</td><td>伊东宽</td><td>21世纪出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>125</td><td>《故障鸟》</td><td>迈克尔·布罗德</td><td>电子工业出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>126</td><td>《断喙鸟》</td><td>纳桑尼·拉胥梅耶</td><td>北京联合出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>127</td><td>《老鼠牙医生》</td><td>威廉·史塔克</td><td>21世纪出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>128</td><td>《小鼹鼠的小蓝天》</td><td>朱莉娅·休伯特</td><td>青岛出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>129</td><td>《外婆住在香水村》</td><td>方素珍</td><td>中国少年儿童出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>130</td><td>《你看起来好像很好吃》系列</td><td>宫西达也</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>131</td><td>《小房子》</td><td>维吉尼亚·李·伯顿</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>132</td><td>《森林大熊》</td><td>约克·史坦纳</td><td>新星出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>133</td><td>《再见小树林》</td><td>严淑女</td><td>河北教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>134</td><td>《村子里来了马戏团》</td><td>小林丰</td><td>21世纪出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>135</td><td>《停电以后》</td><td>约翰罗科</td><td>贵州人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>136</td><td>《荷花镇的早市》</td><td>周翔</td><td>21世纪出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>137</td><td>《旅之绘本-丹麦篇》</td><td>安野光雅</td><td>新星出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>138</td><td>《世界的一天》</td><td>安野光雅</td><td>贵州人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>139</td><td>《环游世界做苹果派》</td><td>玛尤莉·普莱斯曼</td><td>河北教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>140</td><td>《挖土机年年响》</td><td>约克米勒</td><td>新星出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>141</td><td>《下雨了》</td><td>汤姆牛</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>142</td><td>《下雪天》</td><td>艾兹拉·杰克·季兹</td><td>明天出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>143</td><td>《树真好》</td><td>贾尼思·梅</td><td>21世纪出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>144</td><td>《子儿吐吐》</td><td>李瑾伦</td><td>明天出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>145</td><td>《和我一起玩》</td><td>玛丽荷艾斯</td><td>河北教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>146</td><td>《我看见一只鸟》</td><td>刘伯乐</td><td>明天出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>147</td><td>《黄色小蕃茄》</td><td>戴米恩伊莲由美</td><td>青岛出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>148</td><td>《是谁嗯嗯在我的头上》</td><td>霍尔茨瓦特</td><td>河北教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>149</td><td>《夏天的天空》</td><td>彼得史比尔</td><td>中国城市出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>150</td><td>《黎明》</td><td>尤里·舒利瓦茨</td><td>21世纪出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>151</td><td>《一只蓝鸟和一棵树》</td><td>金波</td><td>新蕾出版社</td><td>"3-8岁</td>
		</tr>
		<tr>
			<td>生命之间的美好礼赞"</td>
		</tr>
		<tr>
			<td>152</td><td>《一只想当爸爸的熊》</td><td>﹝德﹞沃尔夫·埃布鲁赫</td><td>广西师范大学出版社</td><td>"3岁以上</td>
		</tr>
		<tr>
			<td>完美回答"我是怎么来的？""</td>
		</tr>
		<tr>
			<td>153</td><td>《第一次见到你》</td><td>杰夫·阿尔茨 著</td><td>电子工业出版社</td><td>"3-6岁</td>
		</tr>
		<tr>
			<td>深情的回应孩子</td>
		</tr>
		<tr>
			<td>关于生命与死亡的追问"</td>
		</tr>
		<tr>
			<td>154</td><td>《一片叶子落下来》</td><td>利奥·巴斯卡利亚　著</td><td>南海出版社</td><td>"3-6岁</td>
		</tr>
		<tr>
			<td>关于生命与死亡的故事"</td>
		</tr>
		<tr>
			<td>155</td><td>《爷爷变成了幽灵》</td><td>（丹麦）金·弗珀兹·艾克松　 </td><td>湖北美术出版社</td><td>"3-6岁</td>
		</tr>
		<tr>
			<td>深情的回应孩子</td>
		</tr>
		<tr>
			<td>关于生命与死亡的追问"</td>
		</tr>
		<tr>
			<td>156</td><td>《獾的礼物》</td><td>（英）华莱　编绘</td><td>明天出版社</td><td>"3-6岁</td>
		</tr>
		<tr>
			<td>关于生命与死亡的故事"</td>
		</tr>
		<tr>
			<td>157</td><td>《再见了，艾玛奶奶》</td><td>（日）大塚敦子 摄影,文字</td><td>南海出版社</td><td>"3-6岁</td>
		</tr>
		<tr>
			<td>关于生命与死亡的故事"</td>
		</tr>
		<tr>
			<td>158</td><td>《活了100万次的猫》</td><td>（日）佐野洋子 著，唐亚明 译</td><td>接力出版社</td><td>"3-6岁</td>
		</tr>
		<tr>
			<td>一部有关生命意义的伟大寓言的绘本"</td>
		</tr>
		<tr>
			<td>159</td><td>《嘘-轻点儿声！》</td><td> 丸山阳子</td><td>希望出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>160</td><td>《一点点儿》</td><td>泷村有子</td><td>光明日报出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>161</td><td>《彼得的椅子》</td><td>（美）季兹</td><td>明天出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>162</td><td>《汤姆的小妹妹》</td><td>（法）玛莉-阿丽娜·巴文</td><td>海燕出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>163</td><td>《我会有个弟弟吗？》</td><td>伊夫·邦廷</td><td>南京师范大学出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>164</td><td>《春天的兔子》</td><td>(英)乔伊斯·顿巴文</td><td>江苏少年儿童出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>165</td><td>《我想有个弟弟》</td><td>（法）克利斯提昂．约里波瓦</td><td>21世纪出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>166</td><td>《小兔子的新宝宝》</td><td>哈里·霍斯</td><td>连环画出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>167</td><td>《又有了一个弟弟》</td><td>（美）科德尔</td><td>21世纪出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>168</td><td>《小凯的家不一样了》</td><td>安东尼·布朗</td><td>河北教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>169</td><td>《富兰克林和小妹妹》</td><td>波莱特·布尔乔亚</td><td>接力出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>170</td><td>《你们都是我的最爱》</td><td>山姆·麦克布·雷尼</td><td>明天出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>171</td><td>《宝宝的摇篮》</td><td>丽贝卡·邦德</td><td>连环画出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>172</td><td>《跟屁虫》</td><td>宫西达也</td><td>21世纪出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>173</td><td>《现在你是哥哥了》</td><td>克劳迪娅·斯科帕</td><td>中华工商联合出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>174</td><td>《现在你是姐姐了》</td><td>克劳迪娅·斯科帕</td><td>中华工商联合出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>175</td><td>《再见，妈妈的奶》</td><td>伴朋子</td><td>北京科学技术出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>176</td><td>《万圣节的大南瓜》</td><td>埃丽卡·西尔弗曼</td><td>南海出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>177</td><td>《飘着幽灵的小房子》</td><td>小原胜野</td><td>湖北美术出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>178</td><td>《女巫扫帚排排坐》</td><td>朱莉娅·唐纳森</td><td>外语教学与研究出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>179</td><td>《女巫科尔娜杜耶》</td><td>皮埃尔·贝特朗</td><td>外语教学与研究出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>180</td><td>《不给糖果就捣蛋》</td><td>斯坦·博丹</td><td>新疆青少年出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>181</td><td>《小女巫》</td><td>广野多珂子</td><td>湖北少儿出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>182</td><td>《妖怪山》</td><td>彭懿</td><td>连环画出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>183</td><td>《极地重生》</td><td>威廉格利尔著绘</td><td>长江少年儿童出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>184</td><td>《猜猜这是谁？》</td><td>陈长海</td><td>山东美术出版社</td><td>"０-3岁</td>
		</tr>
		<tr>
			<td>可以玩的启蒙认知纸板书"</td>
		</tr>
		<tr>
			<td>185</td><td>《你好，你是谁？》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>186</td><td>《大家伙们比大小》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>187</td><td>《小家伙们比大小》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>188</td><td>《巴巴爸爸系列》</td><td>（法）缇森</td><td>接力出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>189</td><td>《好饿的小蛇》</td><td>（日）宫西达也 文/图，彭懿 译</td><td>21世纪出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>190</td><td>《棕色的熊》</td><td>[美]比尔马丁 著</td><td>明天出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>191</td><td>《噼里啪啦系列》</td><td>佐佐木洋子　编绘</td><td>21世纪出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>192</td><td>《可爱的身体》</td><td>（日）七尾纯，小林雅子　文</td><td>南海出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>193</td><td>《宝宝最爱的汽车推拉书》</td><td>（德）达妮埃拉·曹鲁斯</td><td>接力出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>194</td><td>《小熊宝宝系列》</td><td>佐佐木洋子</td><td>连环画出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>195</td><td>《小宝宝翻翻书》</td><td>（英）马梭.普莱斯</td><td>明天出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>196</td><td>《青蛙弗洛格的成长故事》</td><td>（荷兰）马克斯·维尔修思</td><td>湖南少年儿童出版社</td><td>3-7岁</td>
		</tr>
		<tr>
			<td>197</td><td>《小鳄鱼克罗迪和他的朋友》</td><td>（荷兰）马克斯·维尔修思</td><td>新蕾出版社</td><td>3-7岁</td>
		</tr>
		<tr>
			<td>198</td><td>《托马斯和朋友》系列</td><td>&nbsp;</td><td>人民邮电出版社</td><td>3-7岁</td>
		</tr>
		<tr>
			<td>199</td><td>《小熊维尼情绪管理图画书》</td><td>美国迪士尼公司</td><td>童趣出版有限公司</td><td>3-7岁</td>
		</tr>
		<tr>
			<td>200</td><td>《可爱的鼠小弟》1-22</td><td>中江嘉男</td><td>南海出版社</td><td>0-7岁</td>
		</tr>
		<tr>
			<td>201</td><td>《嘟嘟和巴豆系列》</td><td>霍利·霍比　文·图</td><td>21世纪出版社</td><td>3-7岁</td>
		</tr>
		<tr>
			<td>202</td><td>《母鸡萝丝去散步》</td><td>[美]佩特·哈群斯</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>203</td><td>《小狗安格斯系列》</td><td>玛乔丽·弗拉克</td><td>文心出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>204</td><td>《贝贝熊系列丛书》系列</td><td>（美）博丹，（美）博丹 原著</td><td>新疆青少年出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>205</td><td>《14只老鼠全集》</td><td>岩村和朗 著 ,彭懿 译</td><td>接力出版社</td><td>3-7岁</td>
		</tr>
		<tr>
			<td>206</td><td>《三毛新生记》</td><td>张乐平</td><td>少年儿童出版社</td><td>5岁+</td>
		</tr>
		<tr>
			<td>207</td><td>《三毛百趣记》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>208</td><td>《三毛从军记》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>209</td><td>《三毛解放记》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>210</td><td>《三毛流浪记》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>211</td><td>《不睡觉世界冠军》</td><td>几米 图 （英）西恩·泰勒 文</td><td>新星出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>212</td><td>《梦的守护者》</td><td>艾文 格奥舍 </td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>213</td><td>《世界上最大的蛋糕》</td><td>（韩）安英恩 著 </td><td>中信出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>214</td><td>《饭先生和菜小姐》</td><td>（韩）李昭乙 著，袁玲洁 译</td><td>河北少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>215</td><td>《鳄鱼怕怕牙医怕怕》</td><td>五味太郎</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>216</td><td>《肚子里有个火车站》</td><td>（徳）安娜　著，安娜　绘</td><td>北京科学技术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>217</td><td>《牙齿大街的新鲜事》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>218</td><td>《企鹅妈妈的旅程》</td><td>桑德拉·马克尔</td><td>江西高校出版社</td><td>３岁+</td>
		</tr>
		<tr>
			<td>219</td><td>《乌鸦面包店系列》</td><td>（日）加古里子 著</td><td>新星出版社</td><td>5岁+</td>
		</tr>
		<tr>
			<td>220</td><td>《鳄鱼爱上长颈鹿》</td><td>（德）达妮拉·库洛特</td><td>少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>221</td><td>《搬过来，搬过去》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>222</td><td>《天生一对》</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>223</td><td>《迟到大王》</td><td>柏林罕</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>224</td><td>《敌人》</td><td>大卫　文·卡利</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>225</td><td>《你喜欢》</td><td>约翰•柏林罕</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>226</td><td>《和甘伯伯去游河》</td><td>伯宁罕</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>227</td><td>《我讨厌妈妈》</td><td>（日）酒井驹子</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>228</td><td>《生气的亚瑟》</td><td>（英）奥拉姆</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>229</td><td>《野兽出没的地方》</td><td>（美）桑达克</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>230</td><td>《千万别去当海盗》</td><td>（美）梅林达·朗</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>231</td><td>《大雨哗啦哗啦下》</td><td>（美）大卫·香农</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>232</td><td>《要是你给老鼠吃饼干》</td><td>（美国）劳拉·努梅罗夫</td><td>吉林出版集团有限责任公司</td><td>3-6岁</td>
		</tr>
		<tr>
			<td  colspan="5" style="color: red;height:1.5rem">绘本——其它类：</td>
		</tr>
		<tr>
			<td>1</td><td>《爱书的孩子》</td><td>方素珍</td><td>浙江少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>2</td><td>《爱心树》</td><td>（美）希尔弗斯坦　编绘</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>3</td><td>《失落的一角》</td><td>（美）希尔弗斯坦　编绘</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>4</td><td>《猫和鱼》</td><td>琼·格兰特（澳大利亚）文</td><td>北京联合出版公司</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>5</td><td>《三只小猪》</td><td>【美】大卫·威斯纳　文图</td><td>河北少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>6</td><td>《三只小猪的真实故事》</td><td>（美）谢斯卡 文，方素珍 译</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>7</td><td>《冰雪奇缘》</td><td>美国迪士尼公司 著</td><td>人民邮电出版社</td><td>5岁+</td>
		</tr>
		<tr>
			<td>8</td><td>《蚯蚓的日记》</td><td>（美）克罗宁　著</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>9</td><td>《月亮的味道》</td><td>（瑞士）格雷涅茨 著</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>10</td><td>《蚂蚁和西瓜》</td><td>（日）田村茂　文/图</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>11</td><td>《这不是我的帽子》</td><td>[美]乔恩·克拉森</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>12</td><td>《一粒种子的旅行》</td><td>(德) 安妮·默勒　编绘</td><td>南海出版社</td><td>5岁+</td>
		</tr>
		<tr>
			<td>13</td><td>《11只猫》全6册</td><td>﹝日﹞马场登</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>14</td><td>《小黑母鸡》</td><td>（德）施洛斯马赫</td><td>黑龙江少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>15</td><td>《威利和朋友》</td><td>（英）安东尼·布朗</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>16</td><td>《魔术师威利》</td><td>（英）安东尼·布朗</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>17</td><td>《不要睡觉，赛莉》</td><td>（美）莫达瑞西</td><td>江苏少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>18</td><td>《是谁把太阳叫醒的》</td><td>［瑞士］马丁•巴尔切特</td><td>江苏少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>19</td><td>《圣诞老爸》</td><td>（英）雷蒙德·布里格斯</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>20</td><td>《猫头鹰太太去送信》</td><td>（韩）许恩美 </td><td>新疆青少年出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>21</td><td>《方格子老虎》</td><td>（俄罗斯）安德雷·乌萨切夫 </td><td>上海人民美术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>22</td><td>《遮月亮的人》</td><td>[法]埃里克·皮巴雷</td><td>北京科学技术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>23</td><td>《贝尼都会干什么》</td><td>（德）威尔弗里德·盖博哈特 </td><td>江苏少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>24</td><td>《好脏的哈里》系列</td><td>【美】吉恩·蔡恩　文</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>25</td><td>《有个性的羊》</td><td>（德）达尼拉·楚德岑思克</td><td>湖北美术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>26</td><td>《乱扔东西的塔格叔叔》</td><td>（美）李安·布兰肯西普</td><td>南方出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>27</td><td>《大猩猩》</td><td>（英）布朗</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>28</td><td>《打瞌睡的房子》</td><td>（美）伍德</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>29</td><td>《今天运气怎么这么好》</td><td>（日）宫西达也</td><td>南海出版公司</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>30</td><td>《幸运先生和不幸女士》</td><td>（德）安东尼·施奈德</td><td>外语教学与研究出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>31</td><td>《三个强盗》</td><td>（法）温格尔</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>32</td><td>《米歇尔一只倒霉的羊》</td><td>【法】西尔万维克多</td><td>未来出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>33</td><td>《妈妈的礼物》</td><td>（美）古德</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>34</td><td>《狐狸先生的宴会》</td><td>（英）戴维</td><td>湖北美术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>35</td><td>《雪人历险记》</td><td>（奥地利）米拉·洛贝</td><td>湖北美术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>36</td><td>《妈妈以买绿豆》</td><td>曾阳睛</td><td>明天出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>37</td><td>《我不叫亚历山大》</td><td>（美）詹尼弗·福斯伯里</td><td>天津人民美术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>38</td><td>《稀奇古怪的动物园》</td><td>（美）希尔弗斯坦</td><td>南海出版公司</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>39</td><td>《棉花糖的早餐》</td><td>张晋霖，李美华</td><td>中国轻工业出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>40</td><td>《小青椒幼儿园》</td><td>（日）中川宏贵 </td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>41</td><td>《亲爱的小鱼》</td><td>（法）德昂</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>42</td><td>《亚历山大和发条老鼠》</td><td>[美]李欧·李奥尼</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>43</td><td>《吃书的孩子》</td><td>[英]奥利弗·杰夫斯</td><td>接力出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>44</td><td>《图书馆的奇妙事件》</td><td>罗伦茨·保利 </td><td>安徽少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>45</td><td>《蒲公英科学绘本》系列</td><td>金钟贤等</td><td>浙江教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>46</td><td>《奥莉薇》</td><td>伊恩福尔克纳</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>47</td><td>《一只奇特的蛋》</td><td>[美]李欧·李奥尼</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>48</td><td>《浮冰上的小熊》</td><td>(法)安德烈·德昂</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>49</td><td>《卡夫卡变虫计》</td><td>(美)劳伦斯 大卫</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>50</td><td>《动画中国》</td><td>上海美术电影制片厂</td><td>安徽少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>51</td><td>《小墨鱼》</td><td>[美]李欧·李奥尼</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>52</td><td>《颜色的战争》</td><td>(德)爱娃·海勒</td><td>北京科学技术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>53</td><td>《挖鼻孔的大英雄》</td><td>(法)阿兰·麦特</td><td>北京科学技术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>54</td><td>《古利和古拉》系列</td><td>（日）中川李枝子</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>55</td><td>《壁橱里的冒险》</td><td>（日）古田足日</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>56</td><td>《鳄鱼哥尼流》</td><td>（美）李奥尼</td><td>南海出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>57</td><td>《别让鸽子开巴士！》</td><td>（美）威廉斯</td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>58</td><td>《一无所有》</td><td>婉达盖格</td><td>河北少年儿童出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>59</td><td>《小猪小象系列》</td><td>（美）莫·威廉斯</td><td>国际文化出版公司</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>60</td><td>《快乐小猪波波飞》</td><td>高红波</td><td>中国少年儿童出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>61</td><td>《母牛玛塔向前冲》</td><td>（瑞士）热尔马诺·祖罗文</td><td>中国福利会出版社</td><td>0-6岁</td>
		</tr>
		<tr>
			<td>62</td><td>《中国记忆.传统节日》</td><td>王早早</td><td>北京师范大学出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>63</td><td>《讨厌黑夜的席奶奶》</td><td>（美）凯利·杜兰·瑞安</td><td>河北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>64</td><td>《胆小鬼威利》</td><td>安东尼·布朗</td><td>21世纪出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">绘本——科普百科类：</td>
		</tr>
		<tr>
			<td>1</td><td>《恐龙世界大冒险》</td><td>&nbsp;</td><td>接力出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>2</td><td>《交通工具真好玩》</td><td>&nbsp;</td><td>接力出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>3</td><td>《飞行器的大秘密》</td><td>&nbsp;</td><td>接力出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>4</td><td>《我的身体真有趣》</td><td>&nbsp;</td><td>接力出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>5</td><td>《美国经典少儿科学游戏》</td><td>&nbsp;</td><td>接力出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>6</td><td>《飞鼠传奇》</td><td>[德]托本·库曼/著绘 梅思繁/译</td><td>新蕾出版社</td><td>3岁+</td>
		</tr>
		<tr>
			<td>7</td><td>《鼹鼠小镇》</td><td>【德】托本·库曼</td><td>新蕾出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>8</td><td>《这就是二十四节气》</td><td>高春香，邵敏 著</td><td>海豚出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>9</td><td>《德国手绘儿童百科全书》</td><td>Herder出版社</td><td>江西高校出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>10</td><td>《我们，我们的历史》</td><td>"伊万·波莫 克里斯多夫</td>
		</tr>
		<tr>
			<td>伊拉-索梅尔"</td><td>光明日报出版社</td><td>"3-6岁</td>
		</tr>
		<tr>
			<td>一本关于人类文明进化史的书"</td>
		</tr>
		<tr>
			<td>11</td><td>《环游世界》</td><td>"【捷克】B4UPublishing/</td>
		</tr>
		<tr>
			<td>丁郡瑜"</td><td>江西高校出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>12</td><td>《遨游太空》</td><td>"【捷克】B4UPublishing/</td>
		</tr>
		<tr>
			<td>吕凌燕"</td><td>&nbsp;</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>13</td><td>《宝宝最爱的汽车推拉书》</td><td>（德）达妮埃拉·曹鲁斯</td><td>接力出版社</td><td>0-3岁</td>
		</tr>
		<tr>
			<td>14</td><td>《地图（人文版）》</td><td>"【波】亚历山德拉·米热林斯卡</td>
		</tr>
		<tr>
			<td>丹尼尔·米热林斯基　著"</td><td>贵州人民出版社</td><td>5岁+</td>
		</tr>
		<tr>
			<td>15</td><td>《地下水下》</td><td>"【波】亚历山德拉·米热林斯卡</td>
		</tr>
		<tr>
			<td>丹尼尔·米热林斯基　著"</td><td>贵州人民出版社</td><td>5岁+</td>
		</tr>
		<tr>
			<td>16</td><td>《看里面系列》</td><td>"[英]埃里克斯·弗利斯</td>
		</tr>
		<tr>
			<td>[英]科林·金　等著"</td><td>&nbsp;</td><td>"5岁+</td>
		</tr>
		<tr>
			<td>共13册，乐乐趣科普翻翻书"</td>
		</tr>
		<tr>
			<td>17</td><td>《大英儿童百科全书》</td><td>不列颠百科出品，史明　等译</td><td>湖南少儿出版社</td><td>5岁+</td>
		</tr>
		<tr>
			<td>18</td><td>《万物运转的秘密》</td><td>"David Macaulay（大卫·麦考利）</td>
		</tr>
		<tr>
			<td>Neil Ardley（尼尔·阿德利）"</td><td>电子工业出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>19</td><td>第一次发现《手电筒》系列</td><td>法国伽利玛少儿出版社</td><td>接力出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>20</td><td>《可怕的科学》系列</td><td>（英）阿诺备</td><td>北京少年儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>21</td><td>《中国儿童百科全书》</td><td>本书编委会　著</td><td>中国大百科全书出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>22</td><td>《一起来玩科学》系列</td><td>（德）克罗地亚·哈斯</td><td>青岛出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>23</td><td>《魔法科学实验室》</td><td>黄蝶</td><td>海燕出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>24</td><td>《写给小学生的相对论》</td><td>（日）福江纯</td><td>北京科学技术出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>25</td><td>《万物简史》少儿版</td><td>（英）比尔·布莱森</td><td>接力出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>26</td><td>《物种起源》少儿版</td><td>原著：达尔文 </td><td>江西人民出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>27</td><td>《德国少年儿童百科知识全书》</td><td>[德]魏图斯·德略舍尔 </td><td>湖北教育出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>28</td><td>《不一样的大自然绘本》</td><td>[奥]苏珊娜·莉雅 </td><td>北京科学技术出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>29</td><td>《DK儿童历史百科全书》</td><td>英国DK公司</td><td>中信出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>30</td><td>《DK儿童地理百科》</td><td>英国DK公司</td><td>中国大百科全书出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>31</td><td>《DK儿童太空百科全书》</td><td>英国DK公司</td><td>中国大百科全书出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>32</td><td>《DK儿童人体百科》</td><td>英国DK公司</td><td>中国大百科全书出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>33</td><td>《第二次世界大战》</td><td>英国DK公司 </td><td>中国大百科全书出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>34</td><td>《学前儿童为什么小百科》</td><td>英国DK公司 </td><td>中国大百科全书出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>35</td><td>《DK儿童目击者》系列</td><td>英国DK公司</td><td>中国大百科全书出版社</td><td>4-7岁</td>
		</tr>
		<tr>
			<td>36</td><td>《海底小纵队探险记》系列</td><td>英国Vampire Squid Productions有限公司 </td><td>长江少年儿童出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>37</td><td>《金银岛》</td><td>（英）史蒂文森</td><td>作家出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>38</td><td>《荒野求生》</td><td>（英）贝尔·格里尔斯</td><td>接力出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>39</td><td>《吹牛大王历险记》</td><td>（德）拉斯伯·毕尔格</td><td>中国少年儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">幼小衔接必备桥梁书：</td>
		</tr>
		<tr>
			<td>1</td><td>《青蛙和蟾蜍》系列</td><td>艾诺·洛贝尔</td><td>明天出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>2</td><td>《一年级大个子，二年级小个子》</td><td>古田足日</td><td>接力出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>3</td><td>《小狐狸的故事》系列</td><td>森山京</td><td>贵州人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>4</td><td>《阿堇上了一年级》</td><td>石井睦美</td><td>少年儿童出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>5</td><td>《小猪唏哩呼噜》</td><td>孙幼军</td><td>春风文艺出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>6</td><td>《狐狸福斯和兔子哈斯》</td><td>赛尔菲亚·范登·海德 </td><td>贵州人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>7</td><td>《非常小子马鸣加》</td><td>郑春华</td><td>少年儿童出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>8</td><td>《小熊和小狐》</td><td>肖定丽</td><td>少年儿童出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>9</td><td>《小老虎和小熊》</td><td>（德）雅诺什</td><td>新星出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>10</td><td>《小巴掌童话》</td><td>张秋生</td><td>中国少年儿童出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>11</td><td>《花木兰》</td><td>北朝民歌</td><td>明天出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>12</td><td>《文字森林海》</td><td>林世仁</td><td>接力出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>13</td><td>《明天要远足》</td><td>方素珍</td><td>浙江少年儿童出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>14</td><td>《蝴蝶·碗豆花》</td><td>金波</td><td>河北教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>15</td><td>《日有所诵》</td><td>薛瑞萍、徐冬梅、邱凤莲</td><td>广西师范大学出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>16</td><td>《神奇校车·桥梁书版》</td><td>(美)乔安娜柯尔</td><td>贵州人民出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>17</td><td>《昆虫记》</td><td>法布尔　著，奥本大三郎　改编</td><td>北京联合出版公司</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>18</td><td>《西顿动物记》</td><td>欧内斯特·汤普森·西顿</td><td>北京科学技术出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>19</td><td>《小牛顿科学馆》系列</td><td>台湾牛顿出版公司 </td><td>贵州教育出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>20</td><td>《写给中国儿童的历史》系列</td><td>陈卫平</td><td>新世界出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td>21</td><td>《神奇校车.图画书版》</td><td>(美)乔安娜柯尔</td><td>贵州人民出版社</td><td>&nbsp;</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">温暖文字+桥梁系列：</td>
		</tr>
		<tr>
			<td>1</td><td>《小王子》</td><td>尹建莉译</td><td>新蕾出版社</td><td>5岁+</td>
		</tr>
		<tr>
			<td>2</td><td>《笨狼的故事》系列</td><td>汤素兰</td><td>广州出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>3</td><td>《罗尔德.达尔》系列</td><td>罗尔德.达尔</td><td>明天出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>4</td><td>《大侦探福尔摩斯》1-5辑</td><td>柯南道　著，厉河　改编</td><td>湖北教育出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>5</td><td>《彩乌鸦》系列</td><td>"米切尔 恩德</td>
		</tr>
		<tr>
			<td>奥得弗雷德 普鲁士勒</td>
		</tr>
		<tr>
			<td>乌尔苏娜 韦尔芙尔 著"</td><td>21世纪出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>6</td><td>《彩色世界童话全集》</td><td>［丹］安徒生、[德]格林等著</td><td>HarperCollins UK</td><td>6岁+</td>
		</tr>
		<tr>
			<td>7</td><td>《窗边的小豆豆》</td><td>（日）黑柳彻子　著</td><td>南海出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>8</td><td>《哈利波特》系列</td><td>英 J.K.罗琳　著，苏农　等译</td><td>人民文学出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>9</td><td>《淘气包马小跳》系列</td><td>杨红缨</td><td>浙江少年儿童出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>10</td><td>《查理九世》系列</td><td>雷欧幻像</td><td>浙江少年儿童出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>11</td><td>《俏鼠菲姐妹》</td><td>(意)菲·斯蒂顿|译者:孙傲</td><td>北方妇女儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>12</td><td>《玛蒂娜》系列</td><td>（比）徳莱雅文</td><td>贵州教育出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>13</td><td>《玛德琳》系列</td><td>（美）贝梅尔曼斯</td><td>北京联合出版公司</td><td>6岁+</td>
		</tr>
		<tr>
			<td>14</td><td>《鼹鼠的故事》系列</td><td>兹德内克，米勒</td><td>接力出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>15</td><td>《晴天有时下猪》系列</td><td>矢玉四郎　 </td><td>21世纪出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>16</td><td>《怪来佐罗力全》系列</td><td>原裕</td><td>21世纪出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>17</td><td>《木偶奇遇记》</td><td>意）卡洛·科洛迪 著</td><td>中国少年儿童出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>18</td><td>《中国老故事》</td><td>亲近母语研究院 编著</td><td>广西师范大学出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>19</td><td>《郑渊洁四大名传》</td><td>郑渊洁</td><td>浙江少年儿童出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>20</td><td>《小屁孩日记》系列</td><td>[美] 杰夫·金尼 著</td><td>新世纪出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>21</td><td>《长青藤国际大奖小说》系列</td><td>&nbsp;</td><td>晨光出版社</td><td>8岁+</td>
		</tr>
		<tr>
			<td>22</td><td>《国际大奖小说系列》</td><td>（美）卡尔森 等著</td><td>新蕾出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>23</td><td>《夏洛的网》</td><td>（美）怀特　著，任溶溶　译</td><td>上海译文出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>24</td><td>《柳林风声》</td><td>[英]肯尼斯格雷厄姆著</td><td>贵州人民出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>25</td><td>《绿野仙踪》</td><td>鲍姆</td><td>中国少年儿童出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>26</td><td>小淘气尼古拉的故事全集</td><td>（法）勒内·戈西尼　著</td><td>中国少年儿童出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>27</td><td>《丁丁历险记》</td><td>（比利时）埃尔热 编绘</td><td>中国少年儿童出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>28</td><td>《长袜子皮皮》</td><td>（瑞典）林格伦 </td><td>中国少年儿童出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>29</td><td>《时代广场的蟋蟀》</td><td>[美] 乔治塞尔登</td><td>21世纪出版社</td><td>8岁+</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">儿童文学类——文字版：</td>
		</tr>
		<tr>
			<td>1</td><td>《小飞人卡尔松》</td><td>（瑞典)阿斯特丽德·林格伦</td><td>中国少年儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>2</td><td>《大森林里的小木屋》系列</td><td>（美）罗兰·英格斯·怀德</td><td>天地出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>3</td><td>《手斧男孩》系列</td><td>（美）盖瑞·伯森</td><td>吉林文史出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>4</td><td>《老鼠记者》系列</td><td>（意）斯蒂顿</td><td>21世纪出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>5</td><td>《我和小姐姐克拉拉》</td><td>（德）迪米特尔·茵可夫</td><td>21世纪出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>6</td><td>《苹果树上的外婆》</td><td>（奥）洛贝</td><td>新蕾出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>7</td><td>《我的妈妈是精灵》</td><td>陈丹燕</td><td>福建少年儿童出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>8</td><td>《苏菲的世界》</td><td>（挪）贾德</td><td>作家出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>9</td><td>《乌丢丢奇遇》</td><td>金波</td><td>中国少年儿童出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>10</td><td>《不老泉文库》</td><td>[美]娜塔莉·巴比特</td><td>21世纪出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>11</td><td>《曹文轩儿童文学获奖作品》</td><td>曹文轩</td><td>安徽少年儿童出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>12</td><td>《没头脑和不高兴》</td><td>任溶溶</td><td>浙江少年儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>13</td><td>《极地特快》</td><td>（美）奥尔斯伯格</td><td>新星出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>14</td><td>《小狐狸买手套》</td><td>(日) 新美南吉</td><td>中国少年儿童出版社</td><td>6-12岁</td>
		</tr>
		<tr>
			<td>15</td><td>《汤姆叔叔的小屋》</td><td>[美]斯托夫人 </td><td>北方文艺出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>16</td><td>《鲁宾逊漂流记》</td><td>[英]笛福</td><td>北京少年儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>17</td><td>《汤姆·索亚历险记》</td><td>[美]马克·吐温</td><td>北京少年儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>18</td><td>《记忆传授人》</td><td>[美]洛伊丝·劳里</td><td>河北教育出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>19</td><td>《数星星》</td><td>[美]洛伊丝·劳里</td><td>河北教育出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>20</td><td>《碎瓷片》</td><td>[美]  琳达·休·帕克</td><td>河北教育出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>21</td><td>《八十天环游地球》</td><td>[法]儒勒·凡尔纳</td><td>北方文艺出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>22</td><td>《虫虫王国历险记》</td><td>甲壳虫童书馆</td><td>江西高校出版社</td><td>4-7岁</td>
		</tr>
		<tr>
			<td>23</td><td>《世界五千年故事》</td><td>谭树辉</td><td>江西美术出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>24</td><td>《做一个幸福的小孩》</td><td>殷健灵 </td><td>贵州人民出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>25</td><td>《海狸的记号》</td><td>[美]伊丽莎白·乔治·斯皮尔</td><td>河北教育出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>26</td><td>《猫武士》系列</td><td>艾琳·亨特　著，张子默　等译</td><td>未来出版社</td><td>7岁+</td>
		</tr>
		<tr>
			<td>27</td><td>《棚车少年》系列</td><td>[美]钱德勒·华娜 </td><td>长江少年儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">数学历史地理类——文字科普：</td>
		</tr>
		<tr>
			<td>1</td><td>《写给儿童的世界历史》</td><td>陈卫平、林满秋、黄郁彬</td><td>贵州教育出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>2</td><td>《林汉达历史故事》</td><td>林汉达</td><td>中国少年儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>3</td><td>《林汉达上下五千年》</td><td>林汉达</td><td>中国少年儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>4</td><td>《吴姐姐讲历史故事》</td><td>吴涵碧</td><td>新世界出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>5</td><td>《希利尔讲世界史》</td><td>（美）希利尔</td><td>贵州教育出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>6</td><td>《穿越报》</td><td>彭凡</td><td>化学工业出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>7</td><td>《中国古代历史长河图》</td><td>&nbsp;</td><td>星球地图出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>8</td><td>《世界历史大事年表》</td><td>&nbsp;</td><td>中国地图出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>9</td><td>《米先生的世界旅游绘本》</td><td>（捷）M·萨塞克编绘</td><td>安徽少年儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>10</td><td>《写给儿童的中国地理》</td><td>陈卫平、陈雨岚等</td><td>新世界出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>11</td><td>《希利尔讲世界地理》</td><td>（美）希利尔</td><td>贵州教育出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>12</td><td>《你好世界旅游绘本》</td><td>（瑞士）宝莲·巴塞特</td><td>海豚出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>13</td><td>《数学西游戏记》</td><td>李毓佩</td><td>湖北少年儿童出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>14</td><td>《漫画数学》</td><td>（韩）蔡炳夏</td><td>北京科学技术出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>15</td><td>《奇妙的几何》</td><td>（英）格里·贝利、费利西娅·劳</td><td>浙江教育出版社</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>16</td><td>《走进奇妙的数学世界》系列</td><td>安野光雅 </td><td>新星出版社</td><td>3-6岁</td>
		</tr>
		<tr>
			<td>17</td><td>《数学星球》</td><td>[法国]卡莉娜·卢瓦尔</td><td>中国人口出版社</td><td>6-12岁</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">四大名著系列：</td>
		</tr>
		<tr>
			<td>1</td><td>《西游记》</td><td>小人书</td><td>上海人民美术出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>2</td><td>《三国演义》</td><td>&nbsp;</td><td>&nbsp;</td><td>6岁+</td>
		</tr>
		<tr>
			<td>3</td><td>《水浒传》</td><td>&nbsp;</td><td>&nbsp;</td><td>6岁+</td>
		</tr>
		<tr>
			<td>4</td><td>《红楼梦》</td><td>&nbsp;</td><td>&nbsp;</td><td>9岁+</td>
		</tr>
		<tr>
			<td>5</td><td>《西游记》</td><td>吴承恩</td><td>吉林出版集团有限责任公司</td><td>6岁+</td>
		</tr>
		<tr>
			<td>6</td><td>《三国演义》</td><td>罗贯中</td><td>&nbsp;</td><td>6岁+</td>
		</tr>
		<tr>
			<td>7</td><td>《水浒传》</td><td>施耐庵</td><td>&nbsp;</td><td>6岁+</td>
		</tr>
		<tr>
			<td>8</td><td>《红楼梦》</td><td>曹雪芹</td><td>&nbsp;</td><td>9岁+</td>
		</tr>
		<tr>
			<td>9</td><td>《西游记》</td><td>吴承恩</td><td>人民文学出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>10</td><td>《三国演义》</td><td>罗贯中</td><td>&nbsp;</td><td>6岁+</td>
		</tr>
		<tr>
			<td>11</td><td>《水浒传》</td><td>施耐庵</td><td>&nbsp;</td><td>6岁+</td>
		</tr>
		<tr>
			<td>12</td><td>《红楼梦》</td><td>曹雪芹</td><td>&nbsp;</td><td>9岁+</td>
		</tr>
		<tr>
			<td colspan="5" style="color: red;height:1.5rem">其它类：</td>
		</tr>
		<tr>
			<td>1</td><td>中华经典《史记》</td><td>韩兆琦</td><td>中华书局</td><td>7-12岁</td>
		</tr>
		<tr>
			<td>2</td><td>《最美最美的中国童话》</td><td>汉声杂志社 著</td><td>江苏美术出版社</td><td>6岁+</td>
		</tr>
		<tr>
			<td>3</td><td>《一周一首古诗词》</td><td>尹建莉 主编</td><td>作家出版社</td><td>0-18岁</td>
		</tr>
		<tr>
			<td>4</td><td>《爱探险的朵拉》系列</td><td>(美)维内尔|译者:未希</td><td>未来出版社</td><td>3岁+</td>
		</tr>
		<tr>
			<td>5</td><td>《芝麻街》系列</td><td>美国芝麻街工作室</td><td>湖北美术出版社</td><td>3岁+</td>
		</tr>
	</tbody>
</table>	